
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ENT_DEPARTMENT
{

    public long DEP_ID { get; set; }

    public string DEPT_CODE { get; set; }

    public string DEPT_NAME { get; set; }

    public long PARENT_ID { get; set; }

    public string DESC { get; set; }

    public string CREATE_ID { get; set; }

    public Nullable<System.DateTime> CREATE_DATE { get; set; }

    public string MODIFY_ID { get; set; }

    public Nullable<System.DateTime> MODIFY_DATE { get; set; }

    public string MANAGER { get; set; }

}

}
