
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class FIN_EXPENSE_ITEM
{

    public long EXP_ITEM_ID { get; set; }

    public string EXP_FORM_ID { get; set; }

    public string FIN_SUBJECT_ID { get; set; }

    public Nullable<decimal> AMOUNT { get; set; }

    public string ITEM_REMARK { get; set; }

    public Nullable<System.DateTime> MODIFY_DATE { get; set; }

    public string ITEM_UNIT { get; set; }

    public Nullable<decimal> ITEM_UNIT_PRICE { get; set; }

    public Nullable<decimal> ITEM_QUANTITY { get; set; }

}

}
