
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class FIN_LOAN_TRANACTION
{

    public long TID { get; set; }

    public Nullable<long> BL_ID { get; set; }

    public Nullable<int> TRANSACTION_TYPE { get; set; }

    public Nullable<int> PERIOD { get; set; }

    public Nullable<decimal> AMOUNT { get; set; }

    public Nullable<System.DateTime> EVENT_DATE { get; set; }

    public Nullable<System.DateTime> PAYBACK_DATE { get; set; }

    public string REMARK { get; set; }

    public string CREATE_ID { get; set; }

    public Nullable<System.DateTime> CREATE_DATE { get; set; }

    public string MODIFY_ID { get; set; }

    public Nullable<System.DateTime> MODIFY_DATE { get; set; }

    public string VA_FORM_ID { get; set; }

}

}
