
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class FIN_SUBJECT
{

    public string FIN_SUBJECT_ID { get; set; }

    public string SUBJECT_NAME { get; set; }

    public string CATEGORY { get; set; }

    public string BUDGET_DAY { get; set; }

}

}
