
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PLAN_SITE_BUDGET
{

    public long SITE_BUDGET_ID { get; set; }

    public Nullable<int> BUDGET_YEAR { get; set; }

    public Nullable<int> BUDGET_MONTH { get; set; }

    public string SUBJECT_ID { get; set; }

    public Nullable<decimal> AMOUNT { get; set; }

    public string MODIFY_ID { get; set; }

    public Nullable<System.DateTime> CREATE_DATE { get; set; }

    public Nullable<System.DateTime> MODIFY_DATE { get; set; }

    public string PROJECT_ID { get; set; }

    public string YEAR_SEQUENCE { get; set; }

}

}
