
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PLAN_ESTIMATION_ITEM
{

    public long EST_ITEM_ID { get; set; }

    public string EST_FORM_ID { get; set; }

    public string PLAN_ITEM_ID { get; set; }

    public Nullable<decimal> EST_QTY { get; set; }

    public Nullable<decimal> EST_RATIO { get; set; }

    public Nullable<decimal> EST_AMOUNT { get; set; }

    public string REMARK { get; set; }

}

}
