
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PLAN_SUP_INQUIRY_ITEM
{

    public long INQUIRY_ITEM_ID { get; set; }

    public string INQUIRY_FORM_ID { get; set; }

    public string PLAN_ITEM_ID { get; set; }

    public string TYPE_CODE { get; set; }

    public string SUB_TYPE_CODE { get; set; }

    public string ITEM_ID { get; set; }

    public string ITEM_DESC { get; set; }

    public string ITEM_UNIT { get; set; }

    public Nullable<decimal> ITEM_QTY { get; set; }

    public Nullable<decimal> ITEM_UNIT_PRICE { get; set; }

    public Nullable<decimal> ITEM_QTY_ORG { get; set; }

    public Nullable<decimal> ITEM_UNITPRICE_ORG { get; set; }

    public string ITEM_REMARK { get; set; }

    public string MODIFY_ID { get; set; }

    public Nullable<System.DateTime> MODIFY_DATE { get; set; }

    public Nullable<decimal> WAGE_PRICE { get; set; }

    public Nullable<int> ACCUMULATE_QTY { get; set; }

}

}
