
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PLAN_ACCOUNT
{

    public long PLAN_ACCOUNT_ID { get; set; }

    public string PROJECT_ID { get; set; }

    public string CONTRACT_ID { get; set; }

    public string ACCOUNT_FORM_ID { get; set; }

    public Nullable<System.DateTime> PAYMENT_DATE { get; set; }

    public Nullable<decimal> AMOUNT_PAID { get; set; }

    public string ACCOUNT_TYPE { get; set; }

    public string ISDEBIT { get; set; }

    public Nullable<int> STATUS { get; set; }

    public string CREATE_ID { get; set; }

    public string MODIFY_ID { get; set; }

    public Nullable<System.DateTime> MODIFY_DATE { get; set; }

    public string CHECK_NO { get; set; }

    public Nullable<decimal> AMOUNT_PAYABLE { get; set; }

    public Nullable<decimal> BANKING_FEE { get; set; }

    public string PAYEE { get; set; }

    public string REMARK { get; set; }

}

}
