
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PLAN_COSTCHANGE_ITEM
{

    public long ITEM_UID { get; set; }

    public string FORM_ID { get; set; }

    public string PLAN_ITEM_ID { get; set; }

    public string PROJECT_ID { get; set; }

    public string ITEM_ID { get; set; }

    public string ITEM_DESC { get; set; }

    public string ITEM_UNIT { get; set; }

    public Nullable<decimal> ITEM_QUANTITY { get; set; }

    public Nullable<decimal> ITEM_UNIT_PRICE { get; set; }

    public Nullable<decimal> ITEM_UNIT_COST { get; set; }

    public string ITEM_REMARK { get; set; }

    public string MODIFY_USER_ID { get; set; }

    public Nullable<System.DateTime> MODIFY_DATE { get; set; }

    public string CREATE_USER_ID { get; set; }

    public Nullable<System.DateTime> CREATE_DATE { get; set; }

    public Nullable<long> EXCEL_ROW_ID { get; set; }

    public string TRANSFLAG { get; set; }



    public virtual PLAN_COSTCHANGE_FORM PLAN_COSTCHANGE_FORM { get; set; }

}

}
