
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PLAN_DR_ITEM
{

    public long DR_ITEM_ID { get; set; }

    public string PLAN_ITEM_ID { get; set; }

    public string REPORT_ID { get; set; }

    public string PROJECT_ID { get; set; }

    public Nullable<decimal> FINISH_QTY { get; set; }

    public Nullable<decimal> LAST_QTY { get; set; }

    public string REMARK { get; set; }

}

}
