
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PLAN_CERT_ORDER_ITEM
{

    public long CERT_ORD_ITEM_ID { get; set; }

    public string CERT_ORD_ID { get; set; }

    public string PLAN_ITEM_ID { get; set; }

    public string TYPE_CODE { get; set; }

    public string SUB_TYPE_CODE { get; set; }

    public string ITEM_ID { get; set; }

    public string ITEM_DESC { get; set; }

    public string ITEM_UNIT { get; set; }

    public Nullable<decimal> ORDER_QTY { get; set; }

    public Nullable<decimal> ORDER_PRICE { get; set; }

    public Nullable<decimal> ACCUMULTATE_QTY { get; set; }

    public string ITEM_REMARK { get; set; }

    public string MODIFY_ID { get; set; }

    public Nullable<System.DateTime> MODIFY_DATE { get; set; }

    public Nullable<decimal> WAGE_PRICE { get; set; }

}

}
