
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PLAN_PURCHASE_REQUISITION_ITEM
{

    public long PR_ITEM_ID { get; set; }

    public string PR_ID { get; set; }

    public string PLAN_ITEM_ID { get; set; }

    public Nullable<decimal> NEED_QTY { get; set; }

    public Nullable<System.DateTime> NEED_DATE { get; set; }

    public string REMARK { get; set; }

    public Nullable<decimal> ORDER_QTY { get; set; }

    public Nullable<decimal> RECEIPT_QTY { get; set; }

    public string ITEM_DESC { get; set; }

    public string ITEM_UNIT { get; set; }

}

}
