
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PLAN_TASK
{

    public long TASK_ID { get; set; }

    public string PROJECT_ID { get; set; }

    public Nullable<int> PRJ_ID { get; set; }

    public Nullable<int> PRJ_UID { get; set; }

    public string TASK_NAME { get; set; }

    public Nullable<System.DateTime> START_DATE { get; set; }

    public Nullable<System.DateTime> FINISH_DATE { get; set; }

    public Nullable<int> PARENT_UID { get; set; }

    public string DURATION { get; set; }

    public string ROOT_TAG { get; set; }

    public string CREATE_ID { get; set; }

    public Nullable<System.DateTime> CREATE_DATE { get; set; }

    public string MODIFY_ID { get; set; }

    public Nullable<System.DateTime> MODIFY_DATE { get; set; }

}

}
