
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PLAN_ESTIMATION2PURCHASE
{

    public long E2P_ID { get; set; }

    public string PR_ID { get; set; }

    public string EST_FORM_ID { get; set; }

}

}
