
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PLAN_ITEM_DELIVERY
{

    public long DELIVERY_ID { get; set; }

    public string DELIVERY_ORDER_ID { get; set; }

    public string PLAN_ITEM_ID { get; set; }

    public string REMARK { get; set; }

    public string PROJECT_ID { get; set; }

    public Nullable<decimal> DELIVERY_QTY { get; set; }

    public Nullable<System.DateTime> CREATE_DATE { get; set; }

    public string CREATE_USER_ID { get; set; }

    public Nullable<System.DateTime> MODIFY_DATE { get; set; }

    public string MODIFY_USER_ID { get; set; }

}

}
