
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PLAN_BUDGET
{

    public long PLAN_BUDGET_ID { get; set; }

    public string PROJECT_ID { get; set; }

    public string TYPE_CODE_1 { get; set; }

    public string TYPE_CODE_2 { get; set; }

    public string BUDGET_NAME { get; set; }

    public Nullable<decimal> TND_RATIO { get; set; }

    public Nullable<decimal> CONTRACT_AMOUNT { get; set; }

    public Nullable<decimal> BUDGET_AMOUNT { get; set; }

    public Nullable<decimal> BUDGET_RATIO { get; set; }

    public Nullable<decimal> BUDGET_WAGE_AMOUNT { get; set; }

    public Nullable<decimal> BUDGET_WAGE_RATIO { get; set; }

    public string CREATE_ID { get; set; }

    public Nullable<System.DateTime> CREATE_DATE { get; set; }

    public string MODIFY_ID { get; set; }

    public Nullable<System.DateTime> MODIFY_DATE { get; set; }

    public string SYSTEM_MAIN { get; set; }

    public string SYSTEM_SUB { get; set; }

}

}
