
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PLAN_CONTRACT_PROCESS
{

    public string CONTRACT_ID { get; set; }

    public string PROJECT_ID { get; set; }

    public string MATERIAL_BRAND { get; set; }

    public string CONTRACT_PRODUCTION { get; set; }

    public Nullable<System.DateTime> DELIVERY_DATE { get; set; }

    public string REMARK { get; set; }

    public string CREATE_ID { get; set; }

    public Nullable<System.DateTime> CREATE_DATE { get; set; }

    public Nullable<decimal> MAINTENANCE_BOND { get; set; }

    public Nullable<System.DateTime> MB_DUE_DATE { get; set; }

    public string MB_REMARK { get; set; }

    public Nullable<decimal> PERFORMANCE_BOND { get; set; }

    public Nullable<System.DateTime> PB_DUE_DATE { get; set; }

    public string PB_REMARK { get; set; }

}

}
