
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PLAN_VALUATION_FORM
{

    public string VA_FORM_ID { get; set; }

    public string PROJECT_ID { get; set; }

    public Nullable<decimal> VALUATION_AMOUNT { get; set; }

    public Nullable<decimal> TAX_RATIO { get; set; }

    public Nullable<decimal> TAX_AMOUNT { get; set; }

    public Nullable<decimal> RETENTION_PAYMENT { get; set; }

    public Nullable<decimal> ADVANCE_PAYMENT { get; set; }

    public Nullable<decimal> ADVANCE_PAYMENT_REFUND { get; set; }

    public Nullable<decimal> OTHER_PAYMENT { get; set; }

    public string OTHER_PAYMENT_REMARK { get; set; }

    public Nullable<decimal> REPAYMENT { get; set; }

    public string REMARK { get; set; }

    public string CREATE_ID { get; set; }

    public Nullable<System.DateTime> CREATE_DATE { get; set; }

    public Nullable<System.DateTime> MODIFY_DATE { get; set; }

    public Nullable<int> STATUS { get; set; }

}

}
