
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PLAN_PURCHASE_REQUISITION
{

    public string PR_ID { get; set; }

    public string PROJECT_ID { get; set; }

    public Nullable<int> PRJ_UID { get; set; }

    public string RECIPIENT { get; set; }

    public string LOCATION { get; set; }

    public string REMARK { get; set; }

    public string CREATE_USER_ID { get; set; }

    public Nullable<System.DateTime> CREATE_DATE { get; set; }

    public string SUPPLIER_ID { get; set; }

    public string PARENT_PR_ID { get; set; }

    public Nullable<System.DateTime> MODIFY_DATE { get; set; }

    public Nullable<int> STATUS { get; set; }

    public string MEMO { get; set; }

    public string MESSAGE { get; set; }

    public string CAUTION { get; set; }

}

}
