
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PLAN_INDIRECT_COST
{

    public long PKID { get; set; }

    public string PROJECT_ID { get; set; }

    public string FIELD_ID { get; set; }

    public string FIELD_DESC { get; set; }

    public Nullable<decimal> COST { get; set; }

    public Nullable<decimal> PERCENTAGE { get; set; }

    public string NOTE { get; set; }

    public string MODIFY_ID { get; set; }

    public Nullable<System.DateTime> MODIFY_DATE { get; set; }



    public virtual TND_PROJECT TND_PROJECT { get; set; }

}

}
