
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PLAN_ESTIMATION_HOLDPAYMENT
{

    public long HOLD_ID { get; set; }

    public string EST_FORM_ID { get; set; }

    public Nullable<long> PAYMENT_ID { get; set; }

    public string SUPPLIER_ID { get; set; }

    public Nullable<decimal> HOLD_AMOUNT { get; set; }

    public string REMARK { get; set; }



    public virtual PLAN_ESTIMATION_FORM PLAN_ESTIMATION_FORM { get; set; }

}

}
