
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PLAN_DR_TASK
{

    public string REPORT_ID { get; set; }

    public long DR_TASK_ID { get; set; }

    public string PROJECT_ID { get; set; }

    public Nullable<int> PRJ_UID { get; set; }

    public string TASK_NAME { get; set; }

}

}
