
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PLAN_DALIY_REPORT
{

    public string REPORT_ID { get; set; }

    public string PROJECT_ID { get; set; }

    public Nullable<System.DateTime> REPORT_DATE { get; set; }

    public string WEATHER { get; set; }

    public string SUMMARY { get; set; }

    public string SCENE_USER_NAME { get; set; }

    public string SUPERVISION_NAME { get; set; }

    public string OWNER_NAME { get; set; }

    public string MODIFY_USER_ID { get; set; }

    public Nullable<System.DateTime> MODIFY_DATE { get; set; }

    public string CREATE_USER_ID { get; set; }

    public Nullable<System.DateTime> CREATE_DATE { get; set; }

}

}
