
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PLAN_ESTIMATION_PAYMENT_TRANSFER
{

    public long PAYMENT_ID { get; set; }

    public string PAYMENT_FORM_ID { get; set; }

    public string TRANSFER_FORM_ID { get; set; }

    public Nullable<int> ESTIMATION_COUNT { get; set; }

    public Nullable<decimal> PAID_AMOUNT { get; set; }

    public Nullable<decimal> FEE { get; set; }

    public Nullable<decimal> HOLD_AMOUNT { get; set; }

    public Nullable<decimal> CUR_HOLDAMOUNT { get; set; }

    public string REMARK { get; set; }

}

}
