
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PLAN_DR_TEMPWORK
{

    public long ORD_TEMPWORKER_ID { get; set; }

    public string REPORT_ID { get; set; }

    public string SUPPLIER_ID { get; set; }

    public string CHARGE_ID { get; set; }

    public Nullable<decimal> WORKER_QTY { get; set; }

    public Nullable<decimal> LAST_QTY { get; set; }

    public string REMARK { get; set; }

    public string DOC { get; set; }

}

}
