
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PLAN_INVOICE
{

    public long INVOICE_ID { get; set; }

    public string EST_FORM_ID { get; set; }

    public string CONTRACT_ID { get; set; }

    public string INVOICE_NUMBER { get; set; }

    public Nullable<System.DateTime> INVOICE_DATE { get; set; }

    public Nullable<decimal> AMOUNT { get; set; }

    public Nullable<decimal> TAX { get; set; }

    public string TYPE { get; set; }

    public string SUB_TYPE { get; set; }

    public string PLAN_ITEM_ID { get; set; }

    public Nullable<decimal> DISCOUNT_QTY { get; set; }

    public Nullable<decimal> DISCOUNT_UNIT_PRICE { get; set; }

    public Nullable<System.DateTime> CREATE_DATE { get; set; }

}

}
