
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PLAN_TASK2MAPITEM
{

    public long TASKUID { get; set; }

    public string PROJECT_ID { get; set; }

    public Nullable<int> PRJ_UID { get; set; }

    public string MAP_TYPE { get; set; }

    public Nullable<int> MAP_PK { get; set; }

    public string PROJECT_ITEM_ID { get; set; }

}

}
