
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class REF_TYPE_SUB
{

    public int SUB_TYPE_ID { get; set; }

    public string TYPE_CODE_ID { get; set; }

    public Nullable<int> SUB_TYPE_CODE { get; set; }

    public string TYPE_DESC { get; set; }

    public Nullable<System.DateTime> CREATE_DATE { get; set; }

}

}
