
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SYS_KEY_SERIAL
{

    public string KEY_ID { get; set; }

    public string KEY_DESC { get; set; }

    public string PREFIX { get; set; }

    public Nullable<int> KEY_LEN { get; set; }

    public Nullable<long> KEY_NO { get; set; }

    public Nullable<int> QUICK_LEN { get; set; }

}

}
