
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SYS_PARA
{

    public long PARA_ID { get; set; }

    public string FUNCTION_ID { get; set; }

    public string FUNCTION_DESC { get; set; }

    public string FIELD_ID { get; set; }

    public string FIELD_DESC { get; set; }

    public string KEY_FIELD { get; set; }

    public string VALUE_FIELD { get; set; }

}

}
