
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SYS_MESSAGE
{

    public long MSG_ID { get; set; }

    public string FROM_ADDRESS { get; set; }

    public string DISPLAY_NAME { get; set; }

    public string MAIL_LIST { get; set; }

    public string BCC_MAIL_LIST { get; set; }

    public string SUBJECT { get; set; }

    public string MSG_BODY { get; set; }

    public string FILE_PATH { get; set; }

    public Nullable<System.DateTime> SEND_TIME { get; set; }

    public string CREATE_ID { get; set; }

    public Nullable<System.DateTime> CREATE_DATE { get; set; }

    public string STATUS { get; set; }

}

}
