
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SYS_PRIVILEGE
{

    public string PRIVILEGE_ID { get; set; }

    public string ROLE_ID { get; set; }

    public string FUNCTION_ID { get; set; }

    public string ACTION_1_RIGHT { get; set; }

    public string ACTION_1_NAME { get; set; }



    public virtual SYS_FUNCTION SYS_FUNCTION { get; set; }

    public virtual SYS_ROLE SYS_ROLE { get; set; }

}

}
