
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SYS_FUNCTION
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SYS_FUNCTION()
    {

        this.SYS_PRIVILEGE = new HashSet<SYS_PRIVILEGE>();

    }


    public string FUNCTION_ID { get; set; }

    public string FUNCTION_NAME { get; set; }

    public string MODULE_NAME { get; set; }

    public string SUB_MODULE { get; set; }

    public string FUNCTION_URI { get; set; }

    public Nullable<System.DateTime> CREATE_DATE { get; set; }

    public string CREATE_ID { get; set; }

    public Nullable<System.DateTime> MODIFY_DATE { get; set; }

    public string MODIFY_ID { get; set; }

    public string ISMENU { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SYS_PRIVILEGE> SYS_PRIVILEGE { get; set; }

}

}
