
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TND_SUPPLIER
{

    public string SUPPLIER_ID { get; set; }

    public string COMPANY_NAME { get; set; }

    public string COMPANY_ID { get; set; }

    public string CONTACT_NAME { get; set; }

    public string CONTACT_EMAIL { get; set; }

    public string COMPANY_TEL { get; set; }

    public string COMPANY_FAX { get; set; }

    public string CONTACT_MOBILE { get; set; }

    public string SUPPLY_NOTE { get; set; }

    public string REGISTER_ADDRESS { get; set; }

    public string CONTACT_ADDRESS { get; set; }

    public string TYPE_MAIN { get; set; }

    public Nullable<int> TYPE_SUB { get; set; }

}

}
