
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TND_FILE
{

    public long FILE_ID { get; set; }

    public string PROJECT_ID { get; set; }

    public string FILE_UPLOAD_NAME { get; set; }

    public string FILE_ACTURE_NAME { get; set; }

    public string FILE_LOCATIOM { get; set; }

    public string FILE_URL { get; set; }

    public string FILE_TYPE { get; set; }

    public Nullable<System.DateTime> CREATE_DATE { get; set; }

    public string CREATE_ID { get; set; }

}

}
