
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TND_PROJECT_FORM
{

    public string FORM_ID { get; set; }

    public string PROJECT_ID { get; set; }

    public string FORM_NAME { get; set; }

    public string OWNER_NAME { get; set; }

    public string OWNER_TEL { get; set; }

    public string OWNER_EMAIL { get; set; }

    public string OWNER_FAX { get; set; }

    public string SUPPLIER_ID { get; set; }

    public string CONTACT_NAME { get; set; }

    public string CONTACT_EMAIL { get; set; }

    public Nullable<System.DateTime> DUEDATE { get; set; }

    public string REF_ID { get; set; }

    public string CREATE_ID { get; set; }

    public Nullable<System.DateTime> CREATE_DATE { get; set; }

    public string MODIFY_ID { get; set; }

    public Nullable<System.DateTime> MODIFY_DATE { get; set; }

    public string STATUS { get; set; }

    public string ISWAGE { get; set; }

}

}
