
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TND_SUP_MATERIAL_RELATION
{

    public long RELATION_ID { get; set; }

    public string SUPPLIER_ID { get; set; }

    public string TYPE_MAIN { get; set; }

    public Nullable<int> TYPE_SUB { get; set; }

    public string SUPPLY_NOTE { get; set; }

    public string STOP_DELIVERY { get; set; }

}

}
