
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TND_MAP_DEVICE
{

    public long DEVIVE_ID { get; set; }

    public string PROJECT_ID { get; set; }

    public string PROJECT_ITEM_ID { get; set; }

    public string MAP_NO { get; set; }

    public string BUILDING_NO { get; set; }

    public string LOC_DESC { get; set; }

    public Nullable<System.DateTime> CREATE_DATE { get; set; }

    public string CREATE_ID { get; set; }

    public Nullable<decimal> QTY { get; set; }

}

}
