
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TND_PROJECT
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TND_PROJECT()
    {

        this.PLAN_INDIRECT_COST = new HashSet<PLAN_INDIRECT_COST>();

    }


    public string PROJECT_ID { get; set; }

    public string PROJECT_NAME { get; set; }

    public string ENG_NAME { get; set; }

    public string CONTRUCTION_NAME { get; set; }

    public string LOCATION { get; set; }

    public string OWNER_NAME { get; set; }

    public string CONTACT_NAME { get; set; }

    public string CONTACT_TEL { get; set; }

    public string CONTACT_FAX { get; set; }

    public string CONTACT_EMAIL { get; set; }

    public Nullable<System.DateTime> DUE_DATE { get; set; }

    public Nullable<System.DateTime> SCHDL_OFFER_DATE { get; set; }

    public string OWNER_USER_ID { get; set; }

    public string EXCEL_FILE_NAME { get; set; }

    public Nullable<int> START_ROW_NO { get; set; }

    public string STATUS { get; set; }

    public string MODIFY_USER_ID { get; set; }

    public Nullable<System.DateTime> MODIFY_DATE { get; set; }

    public string CREATE_USER_ID { get; set; }

    public Nullable<System.DateTime> CREATE_DATE { get; set; }

    public Nullable<decimal> WAGE_MULTIPLIER { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PLAN_INDIRECT_COST> PLAN_INDIRECT_COST { get; set; }

}

}
