
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TND_SUP_CONTACT_INFO
{

    public long CONTACT_ID { get; set; }

    public string SUPPLIER_MATERIAL_ID { get; set; }

    public string CONTACT_NAME { get; set; }

    public string CONTACT_TEL { get; set; }

    public string CONTACT_FAX { get; set; }

    public string CONTACT_MOBIL { get; set; }

    public string CONTACT_EMAIL { get; set; }

    public string REMARK { get; set; }

}

}
