
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class vw_MAP_PLU
{

    public long PLU_ID { get; set; }

    public string PROJECT_ID { get; set; }

    public string PROJECT_ITEM_ID { get; set; }

    public string MAP_NO { get; set; }

    public string BUILDING_NO { get; set; }

    public string PRIMARY_SIDE { get; set; }

    public string PRIMARY_SIDE_NAME { get; set; }

    public string SECONDARY_SIDE { get; set; }

    public string SECONDARY_SIDE_NAME { get; set; }

    public string PIPE_NAME { get; set; }

    public Nullable<decimal> PIPE_COUNT_SET { get; set; }

    public Nullable<decimal> PIPE_SET_QTY { get; set; }

    public Nullable<decimal> PIPE_LENGTH { get; set; }

    public Nullable<decimal> PIPE_TOTAL_LENGTH { get; set; }

    public Nullable<System.DateTime> CREATE_DATE { get; set; }

    public string CREATE_ID { get; set; }

    public string EXCEL_ITEM { get; set; }

    public string ITEM_DESC { get; set; }

}

}
