
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class WF_PROCESS
{

    public long PID { get; set; }

    public string PROCESS_CODE { get; set; }

    public string PROCESS_NAME { get; set; }

    public string MODIFY_USER_ID { get; set; }

    public Nullable<System.DateTime> MODIFY_DATE { get; set; }

    public string CREATE_USER_ID { get; set; }

    public Nullable<System.DateTime> CREATE_DATE { get; set; }

    public string STATUS { get; set; }

    public string FORM_URL { get; set; }

}

}
