
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class WF_PORCESS_TASK
{

    public long RID { get; set; }

    public long ID { get; set; }

    public string MODIFY_USER_ID { get; set; }

    public Nullable<System.DateTime> MODIFY_DATE { get; set; }

    public string CREATE_USER_ID { get; set; }

    public Nullable<System.DateTime> CREATE_DATE { get; set; }

    public string NOTE { get; set; }

    public string ACTIVITY_TYPE { get; set; }

    public string STATUS { get; set; }

    public string REMARK { get; set; }

    public Nullable<int> SEQ_ID { get; set; }

    public string DEP_CODE { get; set; }

    public string DECISION_USER_ID { get; set; }

}

}
