
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class WF_PROCESS_REQUEST
{

    public long RID { get; set; }

    public string REQ_USER_ID { get; set; }

    public string MODIFY_USER_ID { get; set; }

    public Nullable<System.DateTime> MODIFY_DATE { get; set; }

    public Nullable<System.DateTime> CREATE_DATE { get; set; }

    public Nullable<long> PID { get; set; }

    public string DATA_KEY { get; set; }

    public Nullable<long> CURENT_STATE { get; set; }

}

}
