
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace topmeperp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class WF_PROCESS_ACTIVITY
{

    public long ID { get; set; }

    public Nullable<long> PID { get; set; }

    public string ACTIVITY_NAME { get; set; }

    public string ACTIVITY_CODE { get; set; }

    public string ACTIVITY_TYPE { get; set; }

    public Nullable<int> SEQ_ID { get; set; }

    public string METHOD_URL { get; set; }

    public string DEP_CODE { get; set; }

}

}
